# Generated by Django 5.0.6 on 2024-07-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
            preserve_default=False,
        ),
    ]
